[2024-04-29T12:22:29.258+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T12:22:29.296+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dataset_consumes_1.consuming_1 manual__2024-04-29T12:22:22.496469+00:00 [queued]>
[2024-04-29T12:22:29.306+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dataset_consumes_1.consuming_1 manual__2024-04-29T12:22:22.496469+00:00 [queued]>
[2024-04-29T12:22:29.306+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-29T12:22:29.371+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): consuming_1> on 2024-04-29 12:22:22.496469+00:00
[2024-04-29T12:22:29.381+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=94) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-29T12:22:29.384+0000] {standard_task_runner.py:63} INFO - Started process 96 to run task
[2024-04-29T12:22:29.383+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dataset_consumes_1', 'consuming_1', 'manual__2024-04-29T12:22:22.496469+00:00', '--job-id', '3', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_datasets.py', '--cfg-path', '/tmp/tmpjorzd6m4']
[2024-04-29T12:22:29.387+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask consuming_1
[2024-04-29T12:22:29.472+0000] {task_command.py:426} INFO - Running <TaskInstance: dataset_consumes_1.consuming_1 manual__2024-04-29T12:22:22.496469+00:00 [running]> on host 53b921c79f08
[2024-04-29T12:22:29.703+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dataset_consumes_1' AIRFLOW_CTX_TASK_ID='consuming_1' AIRFLOW_CTX_EXECUTION_DATE='2024-04-29T12:22:22.496469+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-29T12:22:22.496469+00:00'
[2024-04-29T12:22:29.705+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T12:22:29.706+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-29T12:22:29.707+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'sleep 5']
[2024-04-29T12:22:29.733+0000] {subprocess.py:86} INFO - Output:
[2024-04-29T12:22:34.753+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-29T12:22:34.756+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T12:22:34.867+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1564: RemovedInAirflow3Warning: Passing 'execution_date' to 'TaskInstance.xcom_push()' is deprecated.
  context["ti"].xcom_push(key=key, value=value, execution_date=execution_date)

[2024-04-29T12:22:34.926+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dataset_consumes_1, task_id=consuming_1, execution_date=20240429T122222, start_date=20240429T122229, end_date=20240429T122234
[2024-04-29T12:22:35.014+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T12:22:35.039+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T12:22:35.072+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
