[2024-05-01T13:55:21.663+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-01T13:55:21.685+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: try_dag.best_performing_model scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T13:55:21.693+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: try_dag.best_performing_model scheduled__2024-04-30T00:00:00+00:00 [queued]>
[2024-05-01T13:55:21.693+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-05-01T13:55:21.737+0000] {taskinstance.py:2327} INFO - Executing <Task(BranchPythonOperator): best_performing_model> on 2024-04-30 00:00:00+00:00
[2024-05-01T13:55:21.744+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-01T13:55:21.745+0000] {standard_task_runner.py:63} INFO - Started process 94 to run task
[2024-05-01T13:55:21.746+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'try_dag', 'best_performing_model', 'scheduled__2024-04-30T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/sample_dag.py', '--cfg-path', '/tmp/tmppsimj8qb']
[2024-05-01T13:55:21.748+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask best_performing_model
[2024-05-01T13:55:21.856+0000] {task_command.py:426} INFO - Running <TaskInstance: try_dag.best_performing_model scheduled__2024-04-30T00:00:00+00:00 [running]> on host cab22781d943
[2024-05-01T13:55:21.989+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='try_dag' AIRFLOW_CTX_TASK_ID='best_performing_model' AIRFLOW_CTX_EXECUTION_DATE='2024-04-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-30T00:00:00+00:00'
[2024-05-01T13:55:21.991+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-01T13:55:21.991+0000] {baseoperator.py:399} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-05-01T13:55:22.001+0000] {python.py:237} INFO - Done. Returned value was: True
[2024-05-01T13:55:22.001+0000] {branch.py:36} INFO - Branch into True
[2024-05-01T13:55:22.001+0000] {skipmixin.py:178} INFO - Following branch True
[2024-05-01T13:55:22.022+0000] {skipmixin.py:246} INFO - Skipping tasks [('False', -1)]
[2024-05-01T13:55:22.094+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-01T13:55:22.147+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=try_dag, task_id=best_performing_model, execution_date=20240430T000000, start_date=20240501T135521, end_date=20240501T135522
[2024-05-01T13:55:22.200+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-01T13:55:22.235+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-01T13:55:22.283+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
